name: Weekly JPY to EUR Rate Check
on:
  schedule:
    - cron: '0 0 * * 1'  # Runs every Monday at midnight UTC
  workflow_dispatch:  # Allows manual triggering

jobs:
  check-rate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up R
        uses: r-lib/actions/setup-r@v2
        
      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libcurl4-openssl-dev libssl-dev libxml2-dev
          
      - name: Install R packages
        run: |
          R -e 'install.packages(c("httr", "jsonlite", "emayili"), dependencies=TRUE)'
      
      - name: Run R script
        env:
          EXCHANGERATE_API_KEY: ${{ secrets.EXCHANGE_API_KEY }}
          EMAIL_ADDRESS: ${{ secrets.SMTP_USER }}
          EMAIL_PASSWORD: ${{ secrets.SMTP_PASSWORD }}
          RECIPIENT_EMAIL: ${{ secrets.RECIPIENT_EMAIL }}
          PRICE_THRESHOLD: ${{ secrets.PRICE_THRESHOLD }}
        run: Rscript yen_to_euro.R
