name: Weekly JPY to EUR Rate Check

on:
  schedule:
    # Runs every Monday at 9:00 AM UTC
    - cron: '0 9 * * 1'
  
  # Allows manual trigger from GitHub UI
  workflow_dispatch:

jobs:
  monitor-exchange-rate:
    runs-on: ubuntu-latest
    
    env:
      EXCHANGE_API_KEY: ${{ secrets.EXCHANGE_API_KEY }}
      SMTP_SERVER: ${{ secrets.SMTP_SERVER }}
      SMTP_PORT: ${{ secrets.SMTP_PORT }}
      SMTP_USER: ${{ secrets.SMTP_USER }}
      SMTP_PASSWORD: ${{ secrets.SMTP_PASSWORD }}
      RECIPIENT_EMAIL: ${{ secrets.RECIPIENT_EMAIL }}
      PRICE_THRESHOLD: ${{ secrets.PRICE_THRESHOLD }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up R
        uses: r-lib/actions/setup-r@v2
        with:
          r-version: '4.2.0'

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libcurl4-openssl-dev libssl-dev libpng-dev libjpeg-dev libtiff5-dev

      - name: Cache R packages
        uses: actions/cache@v3
        with:
          path: ${{ env.R_LIBS_USER }}
          key: ${{ runner.os }}-r-${{ hashFiles('**/yen_to_euro.R') }}
          restore-keys: ${{ runner.os }}-r-

      - name: Clean cached R packages (Remove dotenv)
        run: |
          Rscript -e 'if ("dotenv" %in% installed.packages()) remove.packages("dotenv")'
        shell: Rscript {0}

      - name: Install R dependencies
        run: |
          Rscript -e 'install.packages(c("httr", "jsonlite", "emayili"), dependencies=TRUE)'
        shell: Rscript {0}

      - name: Run exchange rate monitor
        run: Rscript yen_to_euro.R

      - name: Upload logs
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: exchange-rate-logs
          path: exchange_rate_log.txt
